actors:
  samukei:
    image_url: https://pbs.twimg.com/profile_images/905601706867564544/xFB7rYF5_400x400.jpg
    name: さむけい（藤田）
    url: https://twitter.com/SAMUKEI
  kikuchy:
    image_url: https://pbs.twimg.com/profile_images/481267728/icon_128_400x400.png
    name: kikuchy（菊池）
    url: https://twitter.com/kikuchy
author: 株式会社Diverse
description: Diverse（ダイバース）社員が、会社/事業の魅力と現状をお伝えするPodcast
description_long: 現代の恋愛離れ、未婚率の上昇を解消すべくさまざまな事業を展開する株式会社Diverse（ダイバース）の社員が、会社/事業の魅力と現状をお伝えする広報Podcast
email:
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-4011403-68
hashtag: diverse_inc
twitter_creator: @diverse_inc
itunes_podcast_url:
keywords: love,engineering,programming
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Diverse Podcast
url: https://diverse-podcast.netlify.com/
