actors:
  samukei:
    image_url: https://pbs.twimg.com/profile_images/905601706867564544/xFB7rYF5_400x400.jpg
    name: さむけい（藤田）
    url: https://twitter.com/SAMUKEI
  kikuchy:
    image_url: https://pbs.twimg.com/profile_images/481267728/icon_128_400x400.png
    name: kikuchy（菊池）
    url: https://twitter.com/kikuchy
  amothic:
    image_url: https://pbs.twimg.com/profile_images/867920948133072897/DEMnBFjX_400x400.jpg
    name: とーま（當眞）
    url: https://twitter.com/Amothic
  imaizume:
    image_url: https://pbs.twimg.com/profile_images/970198233816317958/20wB1cKR_400x400.jpg
    name: imaizume（今泉）
    url: https://twitter.com/imaizume
  yotsu:
    image_url: https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/36382010_838188353057300_5198613142174695424_n.jpg?_nc_cat=0&oh=2cdf32fa0dfc93216bc2ab7bfcdb1f88&oe=5C30E05C
    name: yotsu（四柳）
    url: https://www.facebook.com/giiiita42
  kimiyo:
    image_url: https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-1/40397939_2175103442729929_1789606872450334720_o.jpg?_nc_cat=111&oh=539c7b2e8fbb1f897171c332cb090dcb&oe=5C632E39
    name: 田代
    url: https://www.facebook.com/kimiyo.tashiro.9
  kuratsu:
    image_url: https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/12524236_108446329556343_7925953724152118155_n.jpg?_nc_cat=107&oh=ba43127ed080f8bc77932556bb62e183&oe=5C4B8D66
    name: 蔵津
    url: https://www.facebook.com/profile.php?id=100011729285192
author: 株式会社Diverse
description: Diverse（ダイバース）社員が、会社/事業の魅力と現状をお伝えするPodcast
description_long: 現代の恋愛離れ、未婚率の上昇を解消すべくさまざまな事業を展開する株式会社Diverse（ダイバース）の社員が、会社/事業の魅力と現状をお伝えする広報Podcast
email:
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-4011403-68
hashtag: diverse_inc
twitter_creator: "@diverse_inc"
itunes_podcast_url:
keywords: love,engineering,programming
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Diverse Podcast
url: https://podcast.diverse-inc.com
