actors:
  samukei:
    image_url: https://pbs.twimg.com/profile_images/905601706867564544/xFB7rYF5_400x400.jpg
    name: さむけい（藤田）
    url: https://twitter.com/SAMUKEI
  kikuchy:
    image_url: https://pbs.twimg.com/profile_images/481267728/icon_128_400x400.png
    name: kikuchy（菊池）
    url: https://twitter.com/kikuchy
  amothic:
    image_url: https://pbs.twimg.com/profile_images/1054984709132967936/Z2fc3ogZ_400x400.jpg
    name: とーま（當眞）
    url: https://twitter.com/Amothic
  imaizume:
    image_url: https://pbs.twimg.com/profile_images/970198233816317958/20wB1cKR_400x400.jpg
    name: imaizume（今泉）
    url: https://twitter.com/imaizume
  yotsu:
    image_url: https://pbs.twimg.com/profile_images/1045683094903185409/6F6ttya3_400x400.jpg
    name: yotsu（四柳）
    url: https://twitter.com/giiiita_7
  kimiyo:
    image_url: https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-1/40397939_2175103442729929_1789606872450334720_o.jpg?_nc_cat=111&oh=539c7b2e8fbb1f897171c332cb090dcb&oe=5C632E39
    name: 田代
    url: https://www.facebook.com/kimiyo.tashiro.9
  kuratsu:
    image_url: https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-9/12524236_108446329556343_7925953724152118155_n.jpg?_nc_cat=107&_nc_ht=scontent-nrt1-1.xx&oh=c23ba24305b56fd2a67f46fed43028c4&oe=5CE9C166
    name: 蔵津
    url: https://www.facebook.com/profile.php?id=100011729285192
  kanaimarie:
    image_url: https://pbs.twimg.com/profile_images/856888788974317568/1ZW557Cl_400x400.jpg
    name: kanaimarie（金井）
    url: https://twitter.com/kanaimarie
  yoda:
    image_url: https://pbs.twimg.com/profile_images/1092395432989224961/d89pVCw2_400x400.jpg
    name: y-oda（小田）
    url: https://twitter.com/y_oda_dao
  rkowase:
    image_url: https://pbs.twimg.com/profile_images/484707149109411841/PMEVeRs6_400x400.png
    name: rkowase（小和瀬）さん
    url: https://twitter.com/rkowase
  mhidaka:
    image_url: https://pbs.twimg.com/profile_images/1077731257809698818/w0vVKv48_400x400.jpg
    name: mhidaka（日高）さん
    url: https://twitter.com/mhidaka
author: 株式会社Diverse
description: Diverse（ダイバース）社員が、会社/事業の魅力と現状をお伝えするPodcast
description_long: 現代の恋愛離れ、未婚率の上昇を解消すべくさまざまな事業を展開する株式会社Diverse（ダイバース）の社員が、会社/事業の魅力と現状をお伝えする広報Podcast
email:
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-4011403-68
hashtag: diverse_inc
twitter_creator: "@diverse_inc"
itunes_podcast_url:
keywords: love,engineering,programming
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Diverse Podcast
url: https://podcast.diverse-inc.com
